CREATE TABLE notices
(
    id          bigint generated by default as identity primary key,
    user_id     uuid references auth.users not null,
    title text,
    content text,
    done bool,
    inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table notices enable row level security;

create
policy "Individuals can create notices." on notices for
   insert with check (auth.uid() = user_id);

create
policy "Individuals can update their own notices." on notices for
update using (auth.uid() = user_id);

create
policy "Individuals can delete their own notices." on notices for
   delete
using (auth.uid() = user_id);

create
policy "notices are public." on notices for
select using (true);
